### ISSUE TITLE
oc pipeline is failing with the latest version of igc cli (1.37.3)

### ISSUE THREAD

**Issue by RamyaRaghuveera** [cloud-native-toolkit/ibm-garage-cloud-cli#440]
oc pipeline command is failing with the following error on 4.8 Azure IPI cluster & ROSA OCP 4.10 cluster: Error registering pipeline: openshiftRestClient is not a function
igc version: 1.37.3

Complete output while running the command:

? Select the type of pipeline that should be run? Tekton
Creating pipeline on kubernetes cluster in dev-rrb namespace
Retrieving git parameters
Git credentials have already been stored for user: RamyaRaghuveera
  Project git repo: https://github.com/IBM/template-graphql-typescript
  Branch: main
Retrieving available template pipelines from tools
Pipeline templates filtered based on detected runtime: nodejs
? Select the Pipeline to use in the PipelineRun: ibm-nodejs
? scan-image: Enable the pipeline to scan the image for vulnerabilities? No
? lint-dockerfile: Enable the pipeline to lint the Dockerfile for best practices? No
Copying tasks from tools......
Copied Pipeline from tools/ibm-nodejs to dev-rrb/template-graphql-typescript
Creating TriggerTemplate for pipeline: template-graphql-typescript
Creating TriggerBinding for pipeline: template-graphql-typescript
Creating/updating TriggerEventListener for pipeline: tekton
  Waiting for event listener rollout: dev-rrb/el-tekton
Creating/updating Route for pipeline: tekton
Error registering pipeline: openshiftRestClient is not a function

**Comment by RamyaRaghuveera** [comment]
oc pipeline works fine with 1.35 version of igc
